name: Tests

on: [push, pull_request]

jobs:
  gemstash_tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, "3.0", jruby-9.2]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - run: gem update --system
        if: "${{ matrix.ruby == '2.6' || matrix.ruby == '2.5' || matrix.ruby == '2.4' || matrix.ruby == 'jruby-9.2' }}"
      - name: increase ulimit
        run: ulimit -n 8192
      - name: Run Tests
        run: bundle exec rspec --exclude-pattern "spec/integration_spec.rb"
      - name: Run Integration Tests
        run: bundle exec rspec ./spec/integration_spec.rb
    timeout-minutes: 60

