name: Lint

on: [push, pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    env:
      BUNDLE_WITH: "linting"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true # 'bundle install' and cache
    - name: Rubocop
      run: bundle exec rubocop

